spring:
  application:
    name: dance-group-application
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:dance.sqlite
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
